version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: goblog
      DB_TIMEZONE: Asia/Shanghai
    networks:
      - goblog-net

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: goblog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - goblog-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - goblog-net

volumes:
  pgdata:

networks:
  goblog-net:

